# OVERVIEW
# This YAML script will attempt to install a Python virtual environment able to
# support the requirements of a Spatial Data Science or Geocomputation programme.
#
# INSTALLATION
# Note that, in the example commands below, you will need to replace {name} by the name 
# value specified as a configuration parameter below (the first line that does *not* 
# start with a hash (#). All the commands below should be run from the Terminal.
#
#######################
# NOTE: in the below, wherever you see '{name}'
# you should replace that with the name of the 
# environment you are installing (e.g. `sds2020`).
#######################
#
# If you've already installed this environment before:
#   conda remove --name {name} --all
#
# To install/reinstall the environment:
#   conda-env create -f environment.yml
#
# To install/update individual libraries you usually want to force the conda-forge channel:
#   conda install -c conda-forge osmnx
#
# A nice way to set the display name for the environment after activating the env:
#   conda activate {name}
#   python -m ipykernel install --name {name} --display-name "Friendly Name"
# To tidy up environments: 
#   jupyter kernelspec list
#   jupyter kernelspec uninstall unwanted-kernel 
#
# LAUNCH
# You can launch the 'old' notebook server by simply running:
#   jupyter notebook
# The more modern jupyter lab only seems to be launchable from within an environment:
#   conda activate {name}
#   jupyter lab
#
# CONFIGURATION PARAMETERS
name: sds2020
channels:
  - conda-forge
  - defaults
dependencies:
#  - python=3.7  
  - pip 
  - black # Supports code formatter labextension
  - bokeh 
  - cmake
  - contextily
  - contractions
  - cython
  - feather-format 
  - geofeather 
  - geopandas
  - geopy 
  - hdbscan
  - ipyleaflet 
  - ipympl 
  - ipyparallel 
  - ipywidgets 
  - jupyterlab_code_formatter # Supports labextension
  - legendgram
  - mkl-service 
  - mysql-connector-python 
  - nbdime 
  - networkx
  - osmnx
  - nltk>=3.4
  - palettable 
  - pandana # For pysal segregation module
  - pointpats 
  - polyline 
  - psycopg2 
  - pygeos
  - pykrige 
#  - pypdf2 # Overkill
#  - pymc3 # Not well-supported on Windows 
  - pysal
  - python-language-server #Â Supports labextension
  - qgrid 
  - rasterio
  - rasterstats
  - scikit-learn
  - scikit-image
  - seaborn 
  - spacy=2.3.*
  - sqlalchemy
  - statsmodels 
  - tabulate  # For exporting from pandas to markdown
  - textblob # For NLTK/NLP
  - tzlocal 
#- urbanaccess  # For pysal segregation module
  - xlrd 
  - xlsxwriter  
  - pip:
    #- git+http://github.com/sevamoo/SOMPY#egg=sompy # Doesn't run in Python3
    - git+http://github.com/kingsgeocomp/SOMPY#egg=sompy
    - smopy # NOT a typo! Not the same thing as sompy!
    - MulticoreTSNE
    - scikit-posthocs
    - wordcloud
    - jupyter-lsp==0.9.2 # Supports labextension
    - jupyterlab_gitplus # Supports serverextension
    - mgwr 
    - matplotlib-scalebar
    - pymagnitude
#    - pdfkit # Overkill
#    - pypdf2 
#    - pyocr
#    - wand 
